# Конфигурация для ручного деплоя на Render
# Blueprint недоступен в бесплатном плане

services:
  # Backend API Service
  - type: web
    name: voice-chat-backend
    env: python
    pythonVersion: "3.11.9"
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /api/health
    envVars:
      - key: MONGO_URL
        sync: false
        description: "MongoDB Atlas connection string"
      - key: DB_NAME
        value: voice_chat_db
        description: "Database name"
      - key: CORS_ORIGINS
        value: "https://dist-render-test-1.onrender.com,https://dist-render-test.onrender.com"
        description: "Frontend URL for CORS"
      - key: TURN_SERVER_URL
        value: "turn-dist.onrender.com"
        description: "TURN server URL for WebRTC"
    rootDir: backend

  # Frontend Web Service
  - type: web
    name: voice-chat-frontend
    env: node
    buildCommand: yarn install && yarn build
    startCommand: yarn serve
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: "https://dist-render-test.onrender.com"
        description: "Backend service URL"
      - key: REACT_APP_TURN_SERVER_URL
        value: "turn-dist.onrender.com"
        description: "TURN server URL for WebRTC"
      - key: REACT_APP_TURN_PASSWORD
        value: "turn123456"
        description: "TURN server password"
    rootDir: frontend

  # TURN Server для WebRTC
  - type: web
    name: voice-chat-turn
    env: docker
    dockerfilePath: ./turn/Dockerfile.alternative
    dockerContext: ./turn
    envVars:
      - key: TURN_USERNAME
        value: "voicechat"
        description: "TURN server username"
      - key: TURN_PASSWORD
        value: "turn123456"
        description: "TURN server password"
      - key: EXTERNAL_IP
        sync: false
        description: "External IP address (Render автоматически установит)"
    rootDir: turn

# Примечание: MongoDB Atlas нужно настроить отдельно
# Инструкции в README_RENDER_DEPLOY.md
